[package]
name = "file-sort"
version = "0.1.0"
authors = ["Ed Broome <info@sifichi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
stopwatch = "0.0.7"